# Generated by Django 3.1.6 on 2021-02-19 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_auto_20210219_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='cat', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 11, 35, 39, 396830)),
        ),
    ]
